In [72]:
#Create Dependencies

import pandas as pd
import numpy as np
import os

In [73]:
#Create Filepath
df = pd.read_csv("2FiftyCity_ObesityRates.csv")
df.head(50)

,State,City,Obesity %,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,TN,Memphis,35.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TX,Arlington,35.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TX,Fort Worth,35.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TX,Dallas,33.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,MI,Detroit,33.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
5,LA,New Orleans,32.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,KY,Louisville,31.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,OH,Columbus,30.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,VA,Virginia Beach,30.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,OK,Oklahoma City,30.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,OK,Tulsa,30.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,TX,San Antonio,29.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,MO,Kansas City,29.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,TX,Houston,29.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,GA,Atlanta,28.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,TX,El Paso,28.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,FL,Miami,28.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,IN,Indianapolis,28.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,MD,Baltimore,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NC,Charlotte,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,TX,Austin,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,IL,Chicago,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NC,Raleigh,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,CA,Fresno,26.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,AZ,Tucson,26.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,CA,San Diego,26.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,FL,Jacksonville,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,WI,Milwaukee,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,OR,Portland,26.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NE,Omaha,25.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,DC,Washington,25.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,MN,Minneapolis,24.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,TN,Nashville,24.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,PA,Philadelphia,24.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,CA,Long Beach,24.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,CA,Los Angeles,24.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,CA,Sacramento,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,CO,Colorado Springs,23.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NV,Las Vegas,23.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,AZ,Mesa,22.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,AZ,Phoenix,22.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,WA,Seattle,22.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,MA,Boston,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NY,New York,21.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NM,Albuquerque,21.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,CA,San Jose,21.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,CO,Denver,19.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,CA,Oakland,18.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,CA,San Francisco,18.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
df.drop('Unnamed: 3', axis=1, inplace=True)
df.drop('Unnamed: 4', axis=1, inplace=True)
df.drop('Unnamed: 5', axis=1, inplace=True)
df.drop('Unnamed: 6', axis=1, inplace=True)
df.drop('Unnamed: 7', axis=1, inplace=True)
df.drop('Unnamed: 8', axis=1, inplace=True)
df.drop('Unnamed: 9', axis=1, inplace=True)
df.drop('Unnamed: 10', axis=1, inplace=True)
df.drop('Unnamed: 11', axis=1, inplace=True)

In [75]:
df.head(50)

   State              City  Obesity %
0     TN           Memphis       35.8
1     TX         Arlington       35.3
2     TX        Fort Worth       35.3
3     TX            Dallas       33.8
4     MI           Detroit       33.1
5     LA       New Orleans       32.6
6     KY        Louisville       31.2
7     OH          Columbus       30.5
8     VA    Virginia Beach       30.3
9     OK     Oklahoma City       30.1
10    OK             Tulsa       30.1
11    TX       San Antonio       29.8
12    MO       Kansas City       29.5
13    TX           Houston       29.1
14    GA           Atlanta       28.7
15    TX           El Paso       28.6
16    FL             Miami       28.3
17    IN      Indianapolis       28.2
18    MD         Baltimore       28.0
19    NC         Charlotte       28.0
20    TX            Austin       27.0
21    IL           Chicago       27.0
22    NC           Raleigh       27.0
23    CA            Fresno       26.6
24    AZ            Tucson       26.6
25    CA         San Diego       26.1
26    FL      Jacksonville       26.0
27    WI         Milwaukee       26.0
28    OR          Portland       26.0
29    NE             Omaha       25.8
30    DC        Washington       25.2
31    MN       Minneapolis       24.9
32    TN         Nashville       24.7
33    PA      Philadelphia       24.4
34    CA        Long Beach       24.3
35    CA       Los Angeles       24.3
36    CA        Sacramento       24.0
37    CO  Colorado Springs       23.6
38    NV         Las Vegas       23.1
39    AZ              Mesa       22.8
40    AZ           Phoenix       22.8
41    WA           Seattle       22.8
42    MA            Boston       22.0
43    NY          New York       21.9
44    NM       Albuquerque       21.7
45    CA          San Jose       21.2
46    CO            Denver       19.6
47    CA           Oakland       18.2
48    CA     San Francisco       18.2